<?php 
	lista_santos('Enero','enero');
	lista_santos('Febrero','febrero');
	lista_santos('Marzo','marzo');
	lista_santos('Abril','abril');
	lista_santos('Mayo','mayo');
	lista_santos('Junio','junio');
	lista_santos('Julio','julio');
	lista_santos('Agosto','agosto');
	lista_santos('Septiembre','septiembre');
	lista_santos('Octubre','octubre');
	lista_santos('Noviembre','noviembre');
	lista_santos('Diciembre','diciembre');		
 ?>
